baseURL = ""
publishDir = "docs"
languageCode = "en-us"
title = "hello"
theme = "minimal"

[params]
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Georgia"

[[menu.main]]
    url = "/writings/"
    name = "✐"
    weight = 1

[[menu.main]]
    url = "/me/"
    name = "Me"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/podcast/"
    name = "Podcasts"
    weight = 4
    
[[menu.main]]
    url = "/books/"
    name = "Books"
    weight = 5
    
[[menu.main]]
    url = "/quote/"
    name = "Quotes"
    weight = 6
    
[[menu.main]]
    url = "/donors/"
    name = "Donors"
    weight = 7
    
[[menu.main]]
    url = "/music/"
    name = "♫"
    weight = 8

[[menu.icon]]
    url = "https://www.instagram.com/miry_geek/"
    name = "instagram"
    weight = 1

[[menu.icon]]
    url = "https://t.me/miry1919"
    name = "telegram"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/Miry1919/"
    name = "twitter"
    weight = 3
